version: '3'
services:
  client:
    image: 'nsnhatlong/client'
    mem_limit: 128m
    hostname: client
  api:
    image: 'nsnhatlong/api'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'nsnhatlong/worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'nsnhatlong/nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
