name: Deploy MultiDocker

# trigger action when new code push to fullstack-app branch
on:
  push:
    branches:
      - fullstack-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code from github
        uses: actions/checkout@v3
      - name: build dev version of vite-app
        run: docker build ./vite-app -f ./vite-app/Dockerfile.dev -t nsnhatlong/vite-app
      - name: run vite-app in dev mode
        run: docker run nsnhatlong/vite-app npm test run
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get code from github
        uses: actions/checkout@v3
        with:
          branch: fullstack-app
      - name: login to docker account
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # build all the image with production docker files
      - name: build vite container
        run: docker build -t nsnhatlong/vite-app ./vite-app
      - name: build nginx routing container
        run: docker build -t nsnhatlong/nginx ./nginx
      - name: build express container
        run: docker build -t nsnhatlong/express ./express
      - name: build worker container
        run: docker build -t nsnhatlong/worker ./worker

      # push all the image to docker hub
      - name: push vite-app to docker hub
        run: docker push nsnhatlong/vite-app
      - name: push nginx (router) to docker hub
        run: docker push nsnhatlong/nginx
      - name: push express image to docker hub
        run: docker push nsnhatlong/express
      - name: push work image to dockerhub
        run: docker push nsnhatlong/worker
