name: Deploy MultiDocker

# trigger action when new code push to fullstack-app branch
on:
  push:
    branches:
      - fullstack-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code from github
        uses: actions/checkout@v3
      - name: build dev version of client
        run: docker build ./client -f ./client/Dockerfile.dev -t nsnhatlong/client
      - name: run client in dev mode
        run: docker run nsnhatlong/client npm test run
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get code from github
        uses: actions/checkout@v3
        with:
          branch: fullstack-app
      - name: login to docker account
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # build all the image with production docker files
      - name: build vite container
        run: docker build -t nsnhatlong/client ./client
      - name: build nginx routing container
        run: docker build -t nsnhatlong/nginx ./nginx
      - name: build api container
        run: docker build -t nsnhatlong/api ./api
      - name: build worker container
        run: docker build -t nsnhatlong/worker ./worker

      # push all the image to docker hub
      - name: push client to docker hub
        run: docker push nsnhatlong/client
      - name: push nginx (router) to docker hub
        run: docker push nsnhatlong/nginx
      - name: push api image to docker hub
        run: docker push nsnhatlong/api
      - name: push work image to dockerhub
        run: docker push nsnhatlong/worker
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-553837672209
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
